
import logging
from datetime import datetime
from typing import Optional

from app.models.schemas import AnalysisResult

logger = logging.getLogger(__name__)


class ReportGenerator:
    
    def generate_report(
        self,
        analysis: AnalysisResult,
        include_metadata: bool = True
    ) -> str:
        logger.info(f"Generating report for sector: {analysis.sector}")
        
        report_parts = []
        
        if include_metadata:
            report_parts.append(self._generate_metadata(analysis))
        
        report_parts.append(f"# Trade Opportunities Analysis: {analysis.sector.title()} Sector\n")
        report_parts.append(f"*Comprehensive market analysis and trade opportunities for the {analysis.sector} sector in India*\n")
        report_parts.append("---\n")
        
        # Clean up insights - remove extra whitespace and ensure proper formatting
        insights = analysis.insights.strip()
        # Ensure proper spacing between sections
        insights = insights.replace('\n\n\n', '\n\n')
        report_parts.append(insights)
        
        report_parts.append("\n")
        report_parts.append(self._generate_footer())
        
        report = "\n".join(report_parts)
        
        logger.info(f"Report generated ({len(report)} characters)")
        return report
    
    def _generate_metadata(self, analysis: AnalysisResult) -> str:
        metadata = f"""---
sector: {analysis.sector}
generated_at: {analysis.analyzed_at.strftime('%Y-%m-%d %H:%M:%S UTC')}
report_type: Trade Opportunity Analysis
market: India
---
"""
        return metadata
    
    def _generate_footer(self) -> str:
        footer = f"""---

---

*This report was generated by the Trade Opportunities API*  
*Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*

**Disclaimer**: This analysis is for informational purposes only and should not be considered as financial advice. Always conduct your own research and consult with qualified professionals before making investment decisions.
"""
        return footer
    
    def save_report(self, report: str, filename: Optional[str] = None) -> str:
        if not filename:
            timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
            filename = f"market_analysis_{timestamp}.md"
        
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(report)
            logger.info(f"Report saved to {filename}")
            return filename
        except Exception as e:
            logger.error(f"Error saving report: {str(e)}")
            raise


report_generator = ReportGenerator()
